package boletin8_2;

public enum ModeloProcesador {
	INTEL_CORE_I9,INTEL_CORE_I7,INTEL_CORE_I5,INTEL_CORE_I3,INTEL_XEON,INTEL_PENTIUM,INTEL_CELERON,
	AMD_RYZEN_7,AMD_RYZEN_5,AMD_RYZEN_9,AMD_RYZEN_3,AMD_RYZEN_THEREADRIPPER,AMD_EPYC_SERIES
}
